//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace messageBroker {

public class roomIdsVector : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal roomIdsVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(roomIdsVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~roomIdsVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSharpWrapperPINVOKE.delete_roomIdsVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public stringvector roomIds {
    set {
      CSharpWrapperPINVOKE.roomIdsVector_roomIds_set(swigCPtr, stringvector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CSharpWrapperPINVOKE.roomIdsVector_roomIds_get(swigCPtr);
      stringvector ret = (cPtr == global::System.IntPtr.Zero) ? null : new stringvector(cPtr, false);
      return ret;
    } 
  }

  public uint length {
    set {
      CSharpWrapperPINVOKE.roomIdsVector_length_set(swigCPtr, value);
    } 
    get {
      uint ret = CSharpWrapperPINVOKE.roomIdsVector_length_get(swigCPtr);
      return ret;
    } 
  }

  public roomIdsVector() : this(CSharpWrapperPINVOKE.new_roomIdsVector(), true) {
  }

}

}
